### ISSUE TITLE
Leaderboards / COTD results not working 

### ISSUE THREAD

**Issue by bastiHST90** [SoWieMarkus/TrackmaniaCOTDApp#3]
Hi, me again. Sorry 😅
Since a couple of days the cotd results and also the leaderboard doesn't work anymore. Just fyi. I like this app and would love to see it functional again. :)

**Comment by SoWieMarkus** [comment]
Should be fixed again :D Will upload the missing results tomorrow!

**Comment by bastiHST90** [comment]
It isn't showing again. :(

Edit: oh wait, was probably just a hiccup. it works

**Comment by SoWieMarkus** [comment]
Yeah I restarted my server a view times in the last day :D So maybe it was during that time :)
